# Generated by Django 5.0.14 on 2026-08-14 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0012_alter_scansession_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtmRangingObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('distance_mm', models.IntegerField(blank=True, null=True)),
                ('distance_std_dev_mm', models.IntegerField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('num_attempted_measurements', models.IntegerField(blank=True, null=True)),
                ('num_successful_measurements', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('observed_at', models.DateTimeField()),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftm_observations', to='scans.accesspoint')),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftm_observations', to='scans.scansession')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['access_point', 'observed_at'], name='scans_ftmra_access__8fe94e_idx')],
            },
        ),
    ]
