# Generated by Django 5.0.14 on 2026-08-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0013_ftmrangingobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibratedRangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_kind', models.CharField(max_length=16, unique=True)),
                ('ref_rssi_at_1m', models.FloatField()),
                ('path_loss_exponent', models.FloatField()),
                ('r_squared', models.FloatField()),
                ('sample_count', models.IntegerField()),
                ('min_distance_m', models.FloatField()),
                ('max_distance_m', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('fitted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroundTruthPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('AP', 'Access point'), ('OBSERVER', 'Observer position')], max_length=8)),
                ('target_key', models.CharField(max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=128)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['kind'], name='scans_groun_kind_9c04e5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='groundtruthposition',
            constraint=models.UniqueConstraint(fields=('kind', 'target_key'), name='unique_ground_truth_target'),
        ),
    ]
