# Generated by Django 5.0.14 on 2026-08-15 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0014_calibratedrangemodel_groundtruthposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='floorplans/')),
                ('image_width_px', models.IntegerField()),
                ('image_height_px', models.IntegerField()),
                ('anchor1_image_x', models.FloatField(blank=True, null=True)),
                ('anchor1_image_y', models.FloatField(blank=True, null=True)),
                ('anchor1_lat', models.FloatField(blank=True, null=True)),
                ('anchor1_lng', models.FloatField(blank=True, null=True)),
                ('anchor2_image_x', models.FloatField(blank=True, null=True)),
                ('anchor2_image_y', models.FloatField(blank=True, null=True)),
                ('anchor2_lat', models.FloatField(blank=True, null=True)),
                ('anchor2_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='groundtruthposition',
            name='image_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groundtruthposition',
            name='image_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groundtruthposition',
            name='floor_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='scans.floorplan'),
        ),
    ]
