# Generated by Django 5.0.14 on 2026-08-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0015_floorplan_groundtruthposition_image_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='bearing_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='meters_per_pixel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
