# Generated by Django 5.0.14 on 2026-08-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0017_backfill_floorplan_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='outline_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
